version: '2.1'
volumes:
    cloudblockdata:
services:
    cloud:
        build: cloud
        privileged: true
        tty: true
        #restart: always
        network_mode: host
        volumes:
            - 'cloudblockdata:/data'
        depends_on: 
            - "mqtt"
    mqtt:
        image: eclipse-mosquitto:1.6.9
        ports:
            - "1883:1883"
        restart: always
    data_source:
        build: data_source
        #restart: always
        network_mode: host
        privileged: true
        depends_on:
            - "mqtt"
