version: '2.1'
volumes:
    sense-data:
    cloudblockdata:
services:
    cloud:
        build: cloud
        privileged: true
        tty: true
        #restart: always
        network_mode: host
        volumes:
            - 'cloudblockdata:/data'
        environment:
            # connects output from sensor service below
            MQTT_INPUT_TOPIC: sensor_data
        depends_on: 
            - "mqtt"
    mqtt:
        image: eclipse-mosquitto:1.6.9
        ports:
            - "1883:1883"
        restart: always
    sensor:
        image: balenablocks/sensor
        environment:
            # triggers sensor block to push data via MQTT
            MQTT_ADDRESS: localhost
        #restart: always
        network_mode: host
        privileged: true
        labels:
            io.balena.features.kernel-modules: '1'
            io.balena.features.sysfs: '1'
            io.balena.features.balena-api: '1'
        expose:
            - '7575'
        depends_on:
            - "mqtt"
